nama = input("nama saya: ")
umur = input("umur saya: ")
kelas = input("saya kelas: ")
hobi = input("hobi saya: ")
sekolah = input("saya sekolah di: ")
jurusan = input("saya jurusan: ")
rumah = input("rumah saya di: ")
cita2 = input("cita-cita saya")
makanan = input("saya suka makan: ")
warna = input("saya suka warna: ")
print("nama saya",nama,"umur saya",umur,"saya kelas",kelas,"hobi saya",hobi,"saya sekolah di",sekolah,"saya jurusan",jurusan,"rumah saya di",rumah,"cita-cita saya",cita2,"saya suka makan",makanan,"saya suka warna",warna,)
